### ISSUE TITLE
oracle和rdp

### ISSUE THREAD

**Issue by yhy0** [niudaii/go-crack#2]
大佬oracle和rdp是怎么实现的？我正在学习go，也在写，这俩实现不了，求教

**Comment by niudaii** [comment]
> 大佬oracle和rdp是怎么实现的？我正在学习go，也在写，这俩实现不了，求教



> 大佬oracle和rdp是怎么实现的？我正在学习去，梦写，这俩实现不了，求教

oracle可以参考LadonGo，rdp可以参考DarkEye
