### ISSUE TITLE
端口信息匹配导致爆破速度很慢

### ISSUE THREAD

**Issue by yhisme** [niudaii/go-crack#3]
比如3306开放的是http端口，如果对这个http端口进行mysql爆破会导致速度非常慢，作者觉得这个问题需要解决一下吗，因为比如像massscan扫描开放了3306但是不能进行端口识别，如果这样的结果拿去爆破就会导致很慢。

**Comment by niudaii** [comment]
> 3306开放的http端口，如果对这个http端口进行mysql爆破会导致速度非常慢，作者觉得需要解决一下吗，因为像大规模扫描扫描开放了3306但不能进行端口识别，如果这样的结果拿去爆破就会很慢。

go-crack并没有进行端口的指纹识别，这个问题你可以用goby、nmap等有服务指纹识别的端口扫描工具去扫，再把结果用go-crack扫描。最近比较忙，之后有空会重构这个项目🐶

**Comment by yhisme** [comment]
感谢大佬回复，我目前也是采用了masscan+nmap的方案，识别出服务在用go-crack来爆破，还是偶尔会出现不匹配的情况，这样就会导致一两个ip爆破很久的情况，我觉得解决方案可以这样：实时的统计每个ip+端口的平均爆破一次的时间，如果大于某个值就跳过并记录该ip+端口

**Comment by niudaii** [comment]
> 感谢大佬回复，我目前也是采用了masscan+nmap的方案，识别出服务在用go-crack来爆破，还是偶尔会出现不匹配的情况，这样就会导致一两个ip爆破很久的情况，我觉得解决方案可以这样：实时的统计每个ip+端口的平均爆破一次的时间，如果大于某个值就跳过并记录该ip+端口

可以的，有空改

**Comment by niudaii** [comment]
所有爆破协议都做了超时处理，这样就不会出现爆破很久的情况。
