### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Mayter** [niudaii/go-crack#7]
![image](https://user-images.githubusercontent.com/6148807/163688351-a340a4c1-8a8b-4795-819c-c86934f0ea36.png)
首先是我使用了自定义字典但是还是自动加载dict下面的字典

1.输出成功格式顶多做个时间分割而不是删除之前记录重新写入，这样之前记录也存在，也不影响观看。
2.而且界面爆破完成后最好把成功的记录重新用表格的形式展示出来。
3.有时候不光爆破密码，你这个工具爆破成功一个用户就退出了。有时候其它用户也很重要。

**Comment by Mayter** [comment]
还有就是你可以加参数，加了就全爆破默认不加等等

**Comment by niudaii** [comment]
感谢建议，已改进。
![image](https://user-images.githubusercontent.com/41844046/187854720-aab24f21-fa81-4aa1-b3f7-45f543e27450.png)
