### ISSUE TITLE
mysql爆破问题

### ISSUE THREAD

**Issue by V3geD4g** [niudaii/go-crack#8]
本地的mysql可以爆破成功，但是换到服务器的就不行，不知道是什么原因造成的

**Comment by V3geD4g** [comment]
应该是参照了fscan和其他工具的代码，只有连接上去的mnysql有mysql数据库时，才能返回爆破成功，建议改下源码

**Comment by niudaii** [comment]
已修复，设为空即可爆破成功。
![image](https://user-images.githubusercontent.com/41844046/187826300-f75263ff-2aa7-4d41-b489-377748b107e9.png)
